site_name: Documentation
nav: 
  # - Home: index.md
  - R: R.md
  - R Markdown: Rmd.md
  - Matlab: matlab.md
  # - Linux: Linux.md
  - Shell: shell.md
  - Git: git_commands.md
  - TeX: tex.md
  - Web Related: web.md
  - Mkdocs: mkdocs.md

theme:
  name: 'material'
  
markdown_extensions:
  - toc:
      toc_depth: 3