site_name: AC Flower Factory
nav: 
  - Getting Started: index.md
  # - Basic Hybrids: basic-hybrids/index.md
  # - Getting Started: 
  - Basic Hybrids: 
    - Home: basic-hybrids/index.md
  - Breeding Patterns: breeding-patterns.md
  - Mass Production: 
    - Cosmos: mass-production/cosmos.md
    - Windflowers: mass-production/windflowers.md
    - Roses: mass-production/roses.md
  # - R: R.md
  # - R Markdown: Rmd.md
  # - Matlab: matlab.md
  # - Linux: Linux.md
  # - Shell: shell.md
  # - Git: git_commands.md
  # - TeX: tex.md
  # - Web Related: web.md
  # - Mkdocs: mkdocs.md

theme:
  name: 'material'
  palette: 
    primary: teal
  features:
    - tabs
  icon:
    logo: material/flower
    # logo: material/local-florist
  favicon: img/blue-rose2.png
    
markdown_extensions:
  - toc:
      toc_depth: 3
  - pymdownx.tabbed


# 0 148 133