site_name: AC Flower Factory
nav: 
  - Getting Started: index.md
  # - Basic Hybrids: basic-hybrids/index.md
  # - Getting Started: 
  - Basic Hybrids: 
    - Home: basic-hybrids/index.md
    - Mystery Island Hybrids: basic-hybrids/mystery-island.md
  - Breeding Patterns: breeding-patterns.md
  - Mass Production: 
    - Cosmos: mass-production/cosmos.md
    - Windflowers: mass-production/windflowers.md
    - Roses: mass-production/roses.md
  
theme:
  name: 'material'
  palette: 
    primary: teal
  features:
    - tabs
  icon:
    logo: material/flower
    # logo: material/local-florist
  favicon: img/blue-rose2.png
    
markdown_extensions:
  - toc:
      toc_depth: 3
  - pymdownx.tabbed


# 0 148 133